### PR TITLE
More flexible fill-prefix

### LINKED ISSUE #213: comment indentation?
I haven't found any customisation of comment indentation and
the default looks broken:

```
(* start something here...
 then C-j goes 1 space in...
 dadada
 *) 
```

other peoples code comments make me envious:
```
(*   start
     continue...
     more ...
*)
```
what can I do about this? (the indentation, not the envy!)

### PR DESCRIPTION
**Pull request by gabrielhdt**
Set ‘fill-prefix’ to be as many spaces as the length of the comment opener to align first words in comments.

For instance,
```ocaml
(** [foo bar baz] a long documentation that spans over one line,
    first words of each lines are aligned with a M-q call. *)
```
whereas previous behaviour created
```ocaml
(** [foo bar baz] a long documentation that spans over one line,
   first words of each lines are *not* aligned with a M-q call. *)
```

Fixes #213

### CODE REVIEW

**Comment by gadmm** [comment]
Looks interesting, thanks. I would have been interested to try it in my day-to-day activities, but I currently use #209 which works well for me, and I could not manage to adapt the current patch to work together with #209 unfortunately (I am not familiar with the tuareg codebase).

**Comment by gadmm** [comment]
Testing further, it does seem to me that #209 also solves this issue, except in corner cases that I did not discern.

**Comment by gabrielhdt** [comment]
So it seems we have two ways to solve an issue. If #209 is merged upstream, I'm OK with dropping this PR and having a look at the new code (if there is the need).

**Comment by mattiase** [comment]
This PR should be closed (superseded by the merged #271), shouldn't it?

**Pull request closed without merging**
