### PR TITLE
fix(tuareg.el): Fix and improve Emacs bindings

### PR DESCRIPTION
**Pull request by erikmd**
(following the discussion in #273)

Cc @Chris00 @monnier

For a quick recap of the changes and their motivation, see also the table from comment:

https://github.com/ocaml/merlin/issues/1386#issuecomment-1701567716

### CODE REVIEW

**Review by monnier — APPROVED** [review]
LGTM, thanks.
BTW, the ``C-c ` `` binding should be made unnecessary by making `` C-x ` `` work (via `next-error-function`).

**Comment by erikmd** [comment]
Hi @monnier!

Actually I tried to be as conservative as possible, and I'm not sure it is needed to shrink even further the keymap!

Indeed for example, I checked that <code>C-x `</code> and <code>C-c `</code> are both bound in latex-mode from AUCTeX:

```elisp
(let ((test (get-buffer-create "test")))
  (set-buffer test)
  (latex-mode)
  (concat
   (describe-key-briefly (kbd "C-c `"))
   "\n"
   (describe-key-briefly (kbd "C-x `"))))
```
↓
<pre>
"C-c ` runs the command TeX-next-error  
C-x ` runs the command TeX-next-error"
</pre>

**Comment by monnier** [comment]
> Indeed for example, I checked that <code>C-x `</code> and <code>C-c `</code> are both bound in latex-mode from AUCTeX:

Indeed, AUCTeX is another mode that should use `next-error-function`
rather than rebind C-x `  :-)

**Comment by erikmd** [comment]
@Chris00 @monnier are you happy with the current version of this PR?

— I agree with [your earlier comment](https://github.com/ocaml/tuareg/pull/309#pullrequestreview-1605836490) about the fact we could even unbind ``"C-c `"`` but IMHO it is not critical to keep it (all the more as it might surprise some users that use ``"C-c `"`` instead of the generic ``"C-x `"``)…

**Comment by monnier** [comment]
Yes, I already approved the change :-)

**Comment by erikmd** [comment]
Hi, it seems the merlin counterpart of this PR will be merged soon; what about this one?

Anyway, I'd be happy to know @Chris00's opinion, given the three PRs I opened (summarized in [this comment](https://github.com/ocaml/merlin/issues/1386#issuecomment-1701567716)) are basically a follow-up of the wrap-up issue he had opened (https://github.com/ocaml/merlin/issues/1386)

**Pull request merged**
