### PR TITLE
Add font-lock for a list of default types

### PR DESCRIPTION
**Pull request by holomorph**

### CODE REVIEW

**Comment by Chris00** [comment]
The new syntax highlighting rules does not try any more to color all types, only when one introduce a type or for some special constructs.  Not only that was difficult because one needs to understand the structure of the language — think about detecting `(expr: type)` — but this was also too much color which was not really helpful.

**Comment by holomorph** [comment]
Yes, I thought it would be simple compared to other constructs I would like to see highlighted. It would be nice to see modules in their own face, and to see constructors get highlighted.

**Comment by Chris00** [comment]
On Fri, 23 Jan 2015 23:25:11 -0800, holomorph wrote:
> 
> Yes, I thought it would be simple compared to other constructs I would like to
> see highlighted. It would be nice to see modules in their own face, and to see
> constructors get highlighted.

Don't you think it will be too much to also highlight constructors?  In any case, I guess I could do it, using a face with no special properties by default.

**Comment by Chris00** [comment]
On Sat, 24 Jan 2015 10:47:03 +0100, Christophe Troestler wrote:
> 
> On Fri, 23 Jan 2015 23:25:11 -0800, holomorph wrote:
> > 
> > Yes, I thought it would be simple compared to other constructs I would like to see highlighted. It would be nice to see modules in their own face, and to see constructors get highlighted.

I gave it a try and it is working OK but it is hard not to take some
modules too in the regexp.  For example, at first, S in the following
expression was considered a constructor:

module SSet : Set.S with type elt = String.t
                  ^

I tried to be more careful but this is hard: looking at

M(X: t)

is it a functor application or a constructor "M" taking another
constructor "X" of type "t"?

Please try the HEAD and tell me what you think.

**Comment by holomorph** [comment]
> Don't you think it will be too much to also highlight constructors?

Not really, but that must be because I'm accustomed to it from using vim for OCaml. 

Paging through `sample.ml` it appears to do a very good job. M(X: t) as a functor or constructor both seem to do the right thing. I am impressed.

**Comment by Chris00** [comment]
Thanks for checking.

**Pull request closed without merging**
