### PR TITLE
Describe some recent changes in CHANGES.md

### PR DESCRIPTION
**Pull request by mattiase**
I've neglected updating `CHANGES.md`; here is a set of new entries covering most of what I've been up to.
Please tell me if there is a specific style you would like my changes to adhere to.

### CODE REVIEW

**Comment by Chris00** [comment]
Oh, I have been keeping a modified CHANGES.md in my repository but it is not as rich as yours.  I pushed it to https://github.com/ocaml/tuareg/pull/275 so you can see it.  After this PR is merged, would you mind rebasing your changes on top (modifying some entries as what you wrote here is more descriptive that what I wrote).

**Comment by mattiase** [comment]
I'll rebase.

And I just noticed that I've incorrectly put the new entries under version 2.2.0; I suppose there should be a new heading for 2.3.0 (2.4.0?) for any additions – is that right?

**Comment by Chris00** [comment]
Given the number of changes, I was thinking to bump the version to 3.0.

**Comment by mattiase** [comment]
Rebased around your latest changes, with some minor clean-ups of how key bindings are mentioned; hope that is all right.

**Comment by monnier** [comment]
@bbatsov : Done, thanks for the reminder!

**Pull request merged**
